"""day_plans, plan_blocks, recommendation_explanations

Revision ID: 75efdbb41fc5
Revises: 4fea9af5270a
Create Date: 2026-09-13 20:52:00.433866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75efdbb41fc5'
down_revision: Union[str, Sequence[str], None] = '4fea9af5270a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_available_min', sa.Integer(), nullable=False),
    sa.Column('total_requested_min', sa.Integer(), nullable=False),
    sa.Column('unplaced', sa.JSON(), nullable=False),
    sa.Column('conflicts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_day_plans_user_date')
    )
    op.create_index(op.f('ix_day_plans_user_id'), 'day_plans', ['user_id'], unique=False)
    op.create_table('plan_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('day_plan_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.Enum('EVENT', 'TASK', name='blocksourcetype'), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('is_movable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_blocks_day_plan_id'), 'plan_blocks', ['day_plan_id'], unique=False)
    op.create_table('recommendation_explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_block_id', sa.String(length=36), nullable=False),
    sa.Column('user_data_snippet', sa.String(length=500), nullable=False),
    sa.Column('system_rule_snippet', sa.String(length=500), nullable=False),
    sa.Column('evidence_ref_id', sa.String(length=36), nullable=True),
    sa.Column('ai_inference_snippet', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='confidencelevel'), nullable=False),
    sa.ForeignKeyConstraint(['plan_block_id'], ['plan_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_explanations')
    op.drop_index(op.f('ix_plan_blocks_day_plan_id'), table_name='plan_blocks')
    op.drop_table('plan_blocks')
    op.drop_index(op.f('ix_day_plans_user_id'), table_name='day_plans')
    op.drop_table('day_plans')
    # ### end Alembic commands ###
